# Generated by Django 4.2.3 on 2024-08-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('aciklama', models.TextField()),
                ('resim', models.FileField(upload_to='resimler/', verbose_name='Film Resmi')),
                ('yuklenme_tarih', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
